server:
  port: 8085

spring:
  application:
    name: backend
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: ora1234
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  main:
    allow-bean-definition-overriding: true
